import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Providers from "@/components/shared/Providers";
import Header from "@/components/shell/Header";
import BottomNav from "@/components/shell/BottomNav";
import Preloader from "@/components/shared/PreloaderV8";
import SmoothScroll from "@/components/shared/SmoothScroll";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground min-h-screen flex flex-col`}
      >
        <Providers>
          <Preloader />
          <SmoothScroll>
            <Header />
            <main className="flex-1 pb-20 md:pb-0">
              {children}
            </main>
            <BottomNav />
          </SmoothScroll>
        </Providers>
      </body>
    </html>
  );
}
